version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: reserve_system
    working_dir: /var/www
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:stable-alpine
    container_name: reserve_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: reserve_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reserve_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  redis-ui:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    depends_on:
      - redis

networks:
  laravel:

volumes:
  data:
